name: Learn NextJs
run-name: Learn NextJs CI/CD
on: [push]
jobs:
  Development:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Library
        run: yarn
      - name: build
        run: yarn build
  Production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/production' }}
    steps:
      - run: echo "PRD"
