name: Learn NextJs
run-name: Learn NextJs CI/CD
on: [push]
jobs:
  Development:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - name: Set up CheckOut
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Run install
        run: yarn install

      - name: build Development
        run: yarn build

  Production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/production' }}
    steps:
      - run: echo "PRD"
