name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Development:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - run: echo "STG"
  Production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/production' }}
    steps:
      - run: echo "PRD"
